export const options = [
	{ value: 'Bills', label: 'Bills' },
	{ value: 'Business', label: 'Business' },
	{ value: 'Bank Fees', label: 'Bank Fee' },
	{ value: 'Car', label: 'Car' },
	{ value: 'Education/Training', label: 'Education/Training' },
	{ value: 'Entertainment', label: 'Entertainment' },
	{ value: 'Food/Grocery', label: 'Food/Grocery' },
	{ value: 'Gifts', label: 'Gifts' },
	{ value: 'House', label: 'House' },
	{ value: 'Investments', label: 'Investments' },
	{ value: 'Interest', label: 'Interest' },
	{ value: 'Insurance', label: 'Insurance' },
	{ value: 'Kid', label: 'Kid' },
	{ value: 'Legal Fees', label: 'Legal Fees' },
	{ value: 'Medical', label: 'Medical' },
	{ value: 'Online Services', label: 'Online Services' },
	{ value: 'Other', label: 'Other' },
	{ value: 'Pet', label: 'Pet' },
	{ value: 'Phone/Internet', label: 'Phone/Internet' },
	{ value: 'Post/Shipping', label: 'Post/Shipping' },
	{ value: 'Rental', label: 'Rental' },
	{ value: 'Repairs/Maintenance', label: 'Repairs/Maintenance' },
	{ value: 'Restaurant', label: 'Restaurant' },
	{ value: 'Salary', label: 'Salary' },
	{ value: 'Saving', label: 'Saving' },
	{ value: 'Software', label: 'Software' },
	{ value: 'Shopping', label: 'Shopping' },
	{ value: 'Subscriptions/Memberships', label: 'Subscriptions/Memberships' },
	{ value: 'Taxes', label: 'Taxes' },
	{ value: 'Transport', label: 'Transport' },
	{ value: 'Travel', label: 'Travel' },
];

export const categories = options.map((category) => category.value);
